<?php
// insert_products.php – run ONCE, then delete
require_once '../config/db_config.php';

$products = [
    ['americano', 'Americano', 69, '/picture/Americano.png', 'coffee'],
    ['cafe-latte', 'Cafe Latte', 85, '/picture/Cafe Latte.png', 'coffee'],
    ['spanish-latte', 'Spanish Latte', 95, '/picture/Spanish Latte.png', 'popular coffee'],
    ['dirty-matcha', 'Dirty Matcha', 119, '/picture/Dirty Matcha.png', 'coffee'],
    ['dark-mocha', 'Dark Mocha', 139, '/picture/Dark Mocha.png', 'coffee'],
    ['white-mocha', 'White Mocha', 129, '/picture/White Mocha.png', 'popular coffee'],
    ['french-vanilla', 'French Vanilla', 135, '/picture/Franch Vanilla.png', 'popular coffee'],
    ['hazelnut-latte', 'Hazelnut Latte', 135, '/picture/Hazelnut Latte.png', 'coffee'],
    ['strawberry-milk', 'Strawberry Milk', 79, '/picture/Strawberry Milk.png', 'non-coffee'],
    ['blueberry-milk', 'Blueberry Milk', 79, '/picture/Blueberry Milk.png', 'non-coffee'],
    ['milky-oreo', 'Milky Oreo', 85, '/picture/Milky Oreo.png', 'popular non-coffee'],
    ['white-cocoa', 'White Cocoa', 95, '/picture/White cocoa.png', 'non-coffee'],
    ['choco-berry', 'Choco Berry', 109, '/picture/Choco Berry.png', 'popular non-coffee'],
    ['choco-vanilla-cookie', 'Choco Vanilla Cookie', 129, '/picture/Choco Vanilla Cookie.png', 'popular non-coffee'],
    ['choco-banana-pudding', 'Choco Banana Pudding', 179, '/picture/Choco Banana Pudding.png', 'popular non-coffee'],
    ['sea-salt-latte', 'Sea Salt Latte', 115, '/picture/Sea salt Latte.png', 'popular special-coffee'],
    ['salted-mango-dream', 'Salted Mango Dream', 139, '/picture/Salted Mango Dream.png', 'special-coffee'],
    ['berry-caramel-bliss', 'Berry Caramel Bliss', 139, '/picture/Berry Caramel Bliss.png', 'special-coffee'],
    ['caramel-macchiato', 'Caramel Macchiato', 139, '/picture/Caramel Macchiato.png', 'popular special-coffee'],
    ['butterscotch-latte', 'Butter Scotch Latte', 139, '/picture/Butter scotch latte.png', 'special-coffee'],
    ['salted-caramel', 'Salted Caramel', 139, '/picture/Salted Caramel.png', 'popular special-coffee'],
    ['salted-macadamia', 'Salted Macadamia', 139, '/picture/Salted Macadamia.png', 'special-coffee'],
    ['cheesecake-latte', 'Cheesecake Latte', 149, '/picture/Cheesecake Latte.png', 'popular special-coffee'],
    ['einspanner-latte', 'Einspanner Latte', 149, '/picture/SC-Einspanner Latte _ 149 1.png', 'popular special-coffee'],
    ['biscoff-creamy-latte', 'Biscoff Creamy Latte', 159, '/picture/Biscoff Creamy Latte.png', 'popular special-coffee'],
    ['nutella-hazelnut-latte', 'Nutella Hazelnut Latte', 169, '/picture/Nutella Hazelnut latte.png', 'special-coffee'],
    ['tiramisu-latte', 'Tiramisu Latte', 179, '/picture/Tiramisu Latte.png', 'popular special-coffee'],
    ['pure-matcha', 'Pure Matcha', 80, '/picture/Pure matcha.png', 'matcha-fusion'],
    ['matcha-latte', 'Matcha Latte', 85, '/picture/Matcha Latte.png', 'popular matcha-fusion'],
    ['mango-matcha', 'Mango Matcha', 89, '/picture/Mango matcha.png', 'matcha-fusion'],
    ['sea-salt-matcha', 'Sea Salt Matcha', 95, '/picture/Seasalt Matcha.png', 'popular matcha-fusion'],
    ['matcha-freddo', 'Matcha Freddo', 99, '/picture/Matcha Freddo.png', 'popular matcha-fusion'],
    ['choco-matcha', 'Choco Matcha', 109, '/picture/Choco Matcha.png', 'matcha-fusion'],
    ['strawberry-matcha', 'Strawberry Matcha', 115, '/picture/Strawberry Matcha.png', 'popular matcha-fusion'],
    ['cheesecake-matcha', 'Cheesecake Matcha', 80, '/picture/Cheesecake Matcha.png', 'matcha-fusion'],
    ['lavender-matcha', 'Lavender Matcha', 119, '/picture/Lavender Matcha.png', 'matcha-fusion'],
    ['matcha-banana-pudding', 'Matcha Banana Pudding', 179, '/picture/Matcha banana Pudding.png', 'popular matcha-fusion'],
    ['mango-graham', 'Mango Graham', 65, '/picture/Mango graham.png', 'popular fruit-shake'],
    ['strawberry-shake', 'Strawberry Shake', 65, '/picture/Strawberry shake.png', 'fruit-shake'],
    ['blueberry-shake', 'Blueberry Shake', 65, '/picture/BLUEBERRY SHAKE 1.png', 'fruit-shake'],
    ['mango-oreo', 'Mango Oreo', 79, '/picture/mango oreo.png', 'popular fruit-shake'],
    ['berry-oreo', 'Berry Oreo', 79, '/picture/Berry Oreo.png', 'popular fruit-shake'],
    ['berry-mango', 'Berry Mango', 79, '/picture/Berry mango.png', 'popular fruit-shake'],
    ['hershey-delight', 'Hershey Delight', 95, '/picture/FRP-Hershey Delight _ 95 1.png', 'popular frappe-series'],
    ['oreo-frappe', 'Oreo Frappe', 105, '/picture/Oreo Frappe.png', 'popular frappe-series'],
    ['matcha-frappe', 'Matcha Frappe', 105, '/picture/Matcha Frappe.png', 'frappe-series'],
    ['java-chips', 'Java Chips', 199, '/picture/Java Chips.png', 'popular frappe-series'],
    ['cheesecake-frappe', 'Cheesecake Frappe', 129, '/picture/Cheesecake Frappe.png', 'frappe-series'],
    ['white-smore-frappe', 'White Smore Frappe', 129, '/picture/FRP-White Smore CB 129 1.png', 'frappe-series'],
    ['caramel-frappe', 'Caramel Frappe', 139, '/picture/Caramel Frappe.png', 'frappe-series'],
    ['biscoff-frappe', 'Biscoff Frappe', 139, '/picture/Biscoff frappe.png', 'popular frappe-series'],
    ['nutella-hazelnut-frappe', 'Nutella Hazelnut Frappe', 149, '/picture/Nuttela Hazelnut Frappe.png', 'frappe-series'],
    ['waffle-chocolate', 'Lolly Waffle Chocolate', 69, '/picture/Chocolate waffle.png', 'waffles'],
    ['waffle-ube', 'Lolly Waffle Ube', 65, '/picture/ube waffle.png', 'waffles'],
    ['waffle-matcha', 'Lolly Waffle Matcha', 69, '/picture/Matcha waffle.png', 'popular waffles'],
    ['waffle-strawberry', 'Lolly Waffle Strawberry', 69, '/picture/Strawberry waffle.png', 'waffles'],
    ['waffle-oreo', 'Lolly Waffle Oreo', 65, '/picture/Oreo waffle.png', 'popular waffles'],
    ['waffle-tiramisu', 'Lolly Waffle Tiramisu', 75, '/picture/tiramisu waffle.png', 'waffles'],
    ['waffle-biscoff', 'Lolly Waffle Biscoff', 89, '/picture/Biscoff waffle.png', 'popular waffles'],
    ['french-fries', 'French Fries', 69, '/picture/Fries.png', 'bites'],
    ['chicken-poppers', 'Chicken Poppers', 79, '/picture/Chicken Poppers.png', 'bites'],
    ['beef-nachos', 'Beef Nachos', 149, '/picture/Beef Natchos.png', 'bites'],
    ['fries-poppers', 'Fries and Chicken Poppers', 99, '/picture/Chicken poppers and fries.png', 'bites'],
    ['beef-quesadilla', 'Beef Quesadilla', 149, '/picture/Beef Quesadilla.png', 'quesadilla'],
    ['chicken-quesadilla', 'Chicken Quesadilla', 159, '/picture/Chicken Quesadilla.png', 'popular quesadilla'],
    ['messy-tuna-spinach', 'Messy Tuna Spinach', 129, '/picture/Messy Tuna Spinach.png', 'popular quesadilla'],
];

$stmt = $connect->prepare("INSERT INTO products (code, product_name, price, image, category) VALUES (?, ?, ?, ?, ?) ON DUPLICATE KEY UPDATE product_name = VALUES(product_name)");
foreach ($products as $p) {
    $stmt->bind_param("ssdss", $p[0], $p[1], $p[2], $p[3], $p[4]);
    $stmt->execute();
}
echo "Products inserted successfully.";